# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z2_v1.0.xdc/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/T/T.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T || ORIG_REF_NAME==T} -quiet] -quiet

# IP: bd/T/ip/T_processing_system7_0_0/T_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_processing_system7_0_0 || ORIG_REF_NAME==T_processing_system7_0_0} -quiet] -quiet

# IP: bd/T/ip/T_axi_gpio_0_0/T_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_axi_gpio_0_0 || ORIG_REF_NAME==T_axi_gpio_0_0} -quiet] -quiet

# IP: bd/T/ip/T_v_tc_0_0/T_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_v_tc_0_0 || ORIG_REF_NAME==T_v_tc_0_0} -quiet] -quiet

# IP: bd/T/ip/T_v_axi4s_vid_out_0_0/T_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==T_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/T/ip/T_ps7_0_axi_periph_0/T_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_ps7_0_axi_periph_0 || ORIG_REF_NAME==T_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/T/ip/T_rst_ps7_0_100M_0/T_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_rst_ps7_0_100M_0 || ORIG_REF_NAME==T_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/T/ip/T_util_vector_logic_0_0/T_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_util_vector_logic_0_0 || ORIG_REF_NAME==T_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/T/ip/T_xlslice_0_0/T_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_xlslice_0_0 || ORIG_REF_NAME==T_xlslice_0_0} -quiet] -quiet

# IP: bd/T/ip/T_xlslice_0_1/T_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_xlslice_0_1 || ORIG_REF_NAME==T_xlslice_0_1} -quiet] -quiet

# IP: bd/T/ip/T_xlslice_0_2/T_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_xlslice_0_2 || ORIG_REF_NAME==T_xlslice_0_2} -quiet] -quiet

# IP: bd/T/ip/T_xlslice_0_3/T_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_xlslice_0_3 || ORIG_REF_NAME==T_xlslice_0_3} -quiet] -quiet

# IP: bd/T/ip/T_xlslice_4_0/T_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_xlslice_4_0 || ORIG_REF_NAME==T_xlslice_4_0} -quiet] -quiet

# IP: bd/T/ip/T_xlslice_4_1/T_xlslice_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_xlslice_4_1 || ORIG_REF_NAME==T_xlslice_4_1} -quiet] -quiet

# IP: bd/T/ip/T_xlslice_4_2/T_xlslice_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_xlslice_4_2 || ORIG_REF_NAME==T_xlslice_4_2} -quiet] -quiet

# IP: bd/T/ip/T_xbar_0/T_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_xbar_0 || ORIG_REF_NAME==T_xbar_0} -quiet] -quiet

# IP: bd/T/ip/T_v_tpg_0_0/T_v_tpg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_v_tpg_0_0 || ORIG_REF_NAME==T_v_tpg_0_0} -quiet] -quiet

# IP: bd/T/ip/T_auto_pc_0/T_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==T_auto_pc_0 || ORIG_REF_NAME==T_auto_pc_0} -quiet] -quiet

# XDC: bd/T/T_ooc.xdc
